name: Calculator-Application

on:
  push:
    branches: [ developer, main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test & SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests (Unit + Integration)
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Install Sonar Scanner
        run: dotnet tool install --global dotnet-sonarscanner
        shell: bash

      - name: SonarCloud Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"harini-ar-24_CalculatorApplication" \
            /o:"harini-ar-24" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/*/coverage.opencover.xml"

      - name: Build Solution
        run: dotnet build --no-restore

      - name: SonarCloud End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
